CREATE TABLE IF NOT EXISTS trades (
    trade_id TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    market TEXT NOT NULL,
    side TEXT NOT NULL,
    execution_mode TEXT NOT NULL DEFAULT 'live'
);

CREATE TABLE IF NOT EXISTS demo_channels (
    channel_id TEXT PRIMARY KEY,
    payload_json TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    telegram_ref TEXT NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS activity_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts BIGINT NOT NULL,
    kind TEXT NOT NULL,
    payload_json TEXT NOT NULL
);
